# Generated by Django 3.1 on 2020-08-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200828_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='user_password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='user_role',
        ),
    ]
