# Generated by Django 3.0.7 on 2020-09-02 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_creation_date', models.DateField(auto_now_add=True)),
                ('board_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('user_password', models.CharField(max_length=50)),
                ('user_role', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserAndBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Board')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.User')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField()),
                ('task_creation_date', models.DateTimeField(auto_now_add=True)),
                ('task_status', models.CharField(max_length=50)),
                ('task_deadline', models.DateTimeField()),
                ('board_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Board', verbose_name='board_id_of_task')),
            ],
        ),
    ]
