# Generated by Django 3.0.7 on 2020-09-04 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_title', models.CharField(max_length=50, verbose_name='Название доски')),
                ('board_creation_date', models.DateField(auto_now_add=True, verbose_name='Дата создания доски')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField(verbose_name='Описание задачи')),
                ('task_creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания задачи')),
                ('task_deadline', models.DateTimeField(verbose_name='Срок выполнения задачи')),
                ('board_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Board', verbose_name='Задача находится в доске')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True, verbose_name='Имя пользователя')),
                ('user_password', models.CharField(max_length=50, verbose_name='Пароль пользователя')),
                ('user_role', models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('common_user', 'Common user')], default='common_user', max_length=15, verbose_name='Права пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='UserAndTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Task', verbose_name='Номер таска')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.User', verbose_name='Имя пользователя')),
            ],
        ),
    ]
