# Generated by Django 3.0.7 on 2020-09-07 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_title', models.CharField(max_length=50, unique=True, verbose_name='Название доски')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_title', models.CharField(max_length=50, verbose_name='Название колонки')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.CharField(max_length=50, verbose_name='Описание задачи')),
                ('deadline_date', models.DateTimeField(auto_now_add=True)),
                ('board_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Board', verbose_name='Название доски')),
                ('column_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Column', verbose_name='Название колонки')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='BoardsAndUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Board', verbose_name='Название доски')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='BoardAndColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Board', verbose_name='Название доски')),
                ('column_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Column', verbose_name='Название колонки')),
            ],
        ),
    ]
