# Generated by Django 3.0.7 on 2020-09-02 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='board_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Board', verbose_name='Задача находится в доске'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_deadline',
            field=models.DateTimeField(verbose_name='Срок выполнения задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(max_length=50, verbose_name='Статус задачи'),
        ),
    ]
