# Generated by Django 3.1 on 2020-08-17 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserAndBoard',
            fields=[
                ('user_and_board_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('board_title', models.CharField(max_length=150)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApp.user')),
            ],
        ),
    ]
