# Generated by Django 3.1 on 2020-08-17 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardsApp', '0002_auto_20200817_1403'),
        ('usersApp', '0002_auto_20200817_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='userandboard',
            name='board_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardsApp.board'),
        ),
    ]
