# Generated by Django 3.1 on 2020-08-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='creation_date',
            new_name='board_creation_date',
        ),
    ]
