# Generated by Django 3.1 on 2020-08-17 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersApp', '0002_auto_20200817_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField()),
                ('board_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApp.userandboard')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField()),
                ('task_creation_date', models.DateTimeField()),
                ('task_status', models.CharField(max_length=50)),
                ('task_deadline', models.DateField()),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardsApp.board', verbose_name='board_id_of_task')),
            ],
        ),
    ]
